DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     VARCHAR(100)                            NOT NULL,
    uri     VARCHAR(255)                            NOT NULL,
    ip      VARCHAR(15)                             NOT NULL,
    created TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
    );